= Apache Isis - Nightly Builds
:toc:
:toc-title: pass:[<h3>Contents</h3>]
:toc-placement!:

image:https://github.com/apache-isis-committers/isis-nightly/workflows/Nightly/badge.svg[link="https://github.com/apache-isis-committers/isis-nightly/actions?query=workflow%3A%22Nightly%22"]

____
http://isis.apache.org[Apache Isis] software is a framework for rapidly developing domain-driven apps in Java.
Write your business logic in entities, domain services and repositories, and the framework dynamically generates a representation of that domain model as a webapp or a RESTful API.
____

toc::[]

== Artifacts

The following are built and published nightly:

Apache Isis Site::
  * link:https://apache-isis-committers.github.io/isis-nightly[Nightly Preview]
Apache Isis Maven Artifacts::
  * https://repo.incode.work[repo.incode.work]
  * available versions: link:https://repo.incode.work/org/apache/isis/core/isis/maven-metadata.xml[version catalog (xml)]
Docker Images::
  * Demo app, published on Docker Hub as link:https://hub.docker.com/r/apacheisis/isis-2-demo[apacheisis/isis-2-demo]

== Maven

To use the Maven artifacts, add the following definition into your `pom.xml`:

[source,xml]
----
<profiles>
  <profile>
    <id>repo-incode-work</id>
    <activation>
      <property>
        <name>!skip.repo-incode-work</name>
      </property>
    </activation>
    <repositories>
      <repository>
        <releases>
          <enabled>true</enabled>
          <updatePolicy>always</updatePolicy>
          <checksumPolicy>fail</checksumPolicy>
        </releases>
        <snapshots>
          <enabled>false</enabled>
          <updatePolicy>always</updatePolicy>
          <checksumPolicy>fail</checksumPolicy>
        </snapshots>
        <id>repo-incode-work</id>
        <name>Incode Work (maven)</name>
        <url>https://repo.incode.work</url>
      </repository>
    </repositories>
  </profile>
</profiles>
----

[WARNING]
====
These build artifacts are _not_ subject to the Apache Foundation's http://www.apache.org/foundation/governance/[rigorous governance procedures]; use at your own risk.
====

== Docker

The demo-app demonstrates features available in Apache Isis, accompanied by introductory description text. While the demo-app is still work in progress, it might be used to learn the very basics of the framework interactively.

[Note]
====
With the following, <tag> is used as a placeholder for the docker image tag of your choice. Actual tag names might be changed without notice. Currently we have 'springboot'.
====

=== Prereqs

Install https://www.docker.com/community-edition[Docker] on your computer.

=== Pulling the Docker Image

Pull the demo image using:

[source]
----
docker pull apacheisis/isis-2-demo:<tag>
----

This will pull down the latest demo image from https://hub.docker.com/r/apacheisis/isis-2-demo/tags/[Docker hub]

=== Running the Docker Image

Run the demo image using:

[source]
----
docker run --name demo --detach -p8080:8080 apacheisis/isis-2-demo:<tag>
----

This will start a new Docker container named 'demo'.

The demo-app can then be accessed at http://localhost:8080/wicket/[].
Login with `sven:pass`.

To stop and remove the container named 'demo' use:

[source]
----
docker stop demo && docker rm demo
----

=== Customization

To run the _Demo App_ in _prototyping_ mode, add an environment variable `PROTOTYPING=true`.
The 'run' command above then becomes:

[source]
----
docker run --name demo --detach -p8080:8080 -ePROTOTYPING=true apacheisis/isis-2-demo:<tag>
----

To run the container with your console attached, replace the '--detach' argument with '-it'. (Use CTRL-C to stop and detach.)

[source]
----
docker run --name demo -it -p8080:8080 apacheisis/isis-2-demo:<tag>
----
