= Apache Isis - Nightly Builds
:toc:
:toc-title: pass:[<h3>Contents</h3>]
:toc-placement!:

image:https://github.com/apache-isis-committers/isis-nightly/workflows/Nightly/badge.svg[link="https://github.com/apache-isis-committers/isis-nightly/actions?query=workflow%3A%22Nightly%22"]

____
http://isis.apache.org[Apache Isis] software is a framework for rapidly developing domain-driven apps in Java.
Write your business logic in entities, domain services and repositories, and the framework dynamically generates a representation of that domain model as a webapp or a RESTful API.
____

toc::[]

== Artifacts

The following are built and published nightly:

Apache Isis Site::
  * link:https://apache-isis-committers.github.io/isis-nightly[Nightly Preview]
Apache Isis Maven Artifacts::
  * https://repo.incode.work[Staging Repository]
  * Inspect available versions: link:https://repo.incode.work/org/apache/isis/isis-parent/maven-metadata.xml[Version Catalog (XML)]
  * Notes on https://cwiki.apache.org/confluence/display/ISIS/Semantic+Versioning+of+Staged+Builds[Semantic Versioning of Staged Builds]
Docker Images::
  * Demo app, published on Docker Hub as link:https://hub.docker.com/r/apacheisis/demo-wicket[apacheisis/demo-wicket], see https://github.com/apache/isis/tree/master/examples/demo[demo-sources] for details and on how to get started

== Maven

To use the Maven artifacts, add the following definition into your `pom.xml`:

[source,xml]
----
<profiles>
  <profile>
    <id>repo-incode-work</id>
    <activation>
      <property>
        <name>!skip.repo-incode-work</name>
      </property>
    </activation>
    <repositories>
      <repository>
        <releases>
          <enabled>true</enabled>
          <updatePolicy>always</updatePolicy>
          <checksumPolicy>fail</checksumPolicy>
        </releases>
        <snapshots>
          <enabled>false</enabled>
          <updatePolicy>always</updatePolicy>
          <checksumPolicy>fail</checksumPolicy>
        </snapshots>
        <id>repo-incode-work</id>
        <name>Incode Work (maven)</name>
        <url>https://repo.incode.work</url>
      </repository>
    </repositories>
  </profile>
</profiles>
----

[WARNING]
====
These build artifacts are _not_ subject to the Apache Foundation's http://www.apache.org/foundation/governance/[rigorous governance procedures]; use at your own risk.
====
