apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-wicket
spec:
  selector:
    matchLabels:
      app: app-demo-wicket
  replicas: 1
  template:
    metadata:
      labels:
        app: app-demo-wicket
    spec:
      containers:
        - image: apacheisis/demo-wicket:latest
          imagePullPolicy: Always
          name: app-demo-wicket
          env:
            - name: PROTOTYPING
              value: "true"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-wicket
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: app-demo-wicket
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-demo-wicket
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - demo-wicket.isis.incode.work
      secretName: app-demo-wicket-tls
  rules:
    - host: demo-wicket.isis.incode.work
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: app-demo-wicket
                port:
                  number: 80

