name: Nightly


on:
  push: # dummy edit to force build
  schedule:
    ## daily 04:00 (UTC) in the morning
    - cron: '0 4 * * *'

jobs:
  build:
    name: core-and-site
    runs-on: ubuntu-latest
    env:
      # to be shared among all steps of this job
      BASELINE: 2.0.0-M2
      PROJECT_ROOT_PATH: /home/runner/work/isis-nightly/isis
      CI_SCRIPTS_PATH: /home/runner/work/isis-nightly/isis/scripts/ci
      
      NIGHTLY_ROOT_PATH: ${{ github.workspace }}
      NIGHTLY_SCRIPTS_PATH: ${{ github.workspace }}/scripts/nightly
      
      # used for printing
      TIMESTAMP: ${{ github.event.head_commit.timestamp }}

      # 'deploy' to push to repo, 'install' otherwise
      MVN_STAGES: deploy

    steps:
    - name: Checkout Nightly
      uses: actions/checkout@v1
      
    - name: Calculate new Revision (if changed since last published, else skip)
      id: revision
      run: bash $NIGHTLY_SCRIPTS_PATH/new-revision.sh
    
    - name: Checkout Apache Isis
      if: steps.revision.outputs.revision != 'skip'
      uses: actions/checkout@v1
      with:
        repository: apache/isis
        ref: refs/heads/master
        token: ${{ secrets.GitHub_PAT }}
    
    - name: Set up JDK 11
      if: steps.revision.outputs.revision != 'skip'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Print Maven Version
      if: steps.revision.outputs.revision != 'skip'
      run: mvn --version
    
    - name: Setup Script Environment
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      # prints all the (non-secret) variables as used by the build scripts to the console
      run: |
        echo ==============  ENV  =================
        echo BASELINE            \: $BASELINE
        echo TIMESTAMP           \: $TIMESTAMP
        echo PROJECT_ROOT_PATH   \: $PROJECT_ROOT_PATH
        echo CI_SCRIPTS_PATH     \: $CI_SCRIPTS_PATH
        echo NIGHTLY_ROOT_PATH   \: $NIGHTLY_ROOT_PATH
        echo NIGHTLY_SCRIPTS_PATH\: $NIGHTLY_SCRIPTS_PATH
        echo MVN_STAGES          \: $MVN_STAGES
        echo REVISION            \: $REVISION
        echo ======================================
      env:
        REVISION: ${{ steps.revision.outputs.revision }}

     ## gh-packages: does not work consistently as of 2019-11-12, maybe try again after beta phase    
    - name: Build and Push Core (github packages)
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      working-directory: ${{ env.PROJECT_ROOT_PATH }}
      run: |
        bash $CI_SCRIPTS_PATH/build-core.sh
      env:
        REVISION: ${{ steps.revision.outputs.revision }}
        ## github packages
        GH_DEPLOY_OWNER: apache-isis-committers
        GH_DEPLOY_TOKEN: ${{ secrets.WRITE_REPO_AND_PACKAGES_TOKEN }}
        MVN_ADDITIONAL_OPTS: '-DaltReleaseDeploymentRepository=github::default::https://maven.pkg.github.com/apache-isis-committers/isis-nightly'

    - name: Build and Push Core (GCP)
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      working-directory: ${{ env.PROJECT_ROOT_PATH }}
      run: |
        bash $CI_SCRIPTS_PATH/build-core.sh
      env:
        REVISION: ${{ steps.revision.outputs.revision }}
        ## GCP App Engine: repo.incode.work
        GCPAPPENGINEREPO_USERNAME: ${{ secrets.GCPAPPENGINEREPO_USERNAME }}
        GCPAPPENGINEREPO_PASSWORD: ${{ secrets.GCPAPPENGINEREPO_PASSWORD }}
        MVN_ADDITIONAL_OPTS: '-DaltReleaseDeploymentRepository=gcpappenginerepo::default::https://repo.incode.work'
        SETTINGS_XML: ${{ env.PROJECT_ROOT_PATH }}/.m2/settings.xml
 
    - name: Build and Push Demo-App (Docker Hub)
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      run: |
        bash $CI_SCRIPTS_PATH/build-demo-app.sh springboot
      env:
        REVISION: ${{ steps.revision.outputs.revision }}
        ## DOCKER HUB
        DOCKER_REGISTRY_USERNAME: apacheisiscommitters
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        DOCKER_REGISTRY_URL: 'https://index.docker.io/v1/'
    
    # ------------------------
    # -- now build the site --
    # ------------------------
        
    - name: Print Node Version
      if: steps.revision.outputs.revision != 'skip'
      run: node --version

    - name: Install NVM
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      run: bash $CI_SCRIPTS_PATH/install-nvm.sh
      
    - name: Install Antora
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      working-directory: ${{ env.PROJECT_ROOT_PATH }}
      # we install the 'node' modules into the project root under 'node_modules', 
      # because we have no privileges to install them globally with -g option
      run: npm i @antora/cli@2.2 @antora/site-generator-default@2.2 asciidoctor-plantuml@1.3.1
      
    - name: Print Antora Version
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      working-directory: ${{ env.PROJECT_ROOT_PATH }}
      run: $(npm bin)/antora version
      
    - name: Setup Groovy
      if: steps.revision.outputs.revision != 'skip'
      run: sudo apt-get -f install groovy
      
    - name: Print Groovy Version
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      run: groovy --version 
    
    - name: Build Apache Isis Site
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      working-directory: ${{ env.PROJECT_ROOT_PATH }}
      # builds static web content into ${PROJECT_ROOT_PATH}/antora/target/site,
      # as specified in the site.yml file
      run: |
        bash $NIGHTLY_SCRIPTS_PATH/patch-site-config.sh ${PROJECT_ROOT_PATH}/site.yml
        bash $CI_SCRIPTS_PATH/build-site.sh site.yml
      env:
        REVISION: ${{ steps.revision.outputs.revision }}
      
    - name: Rsync Site Content to Nightly Working Tree
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      run: bash $NIGHTLY_SCRIPTS_PATH/rsync-site.sh 
      
    - name: Commit Site Update
      if: steps.revision.outputs.revision != 'skip'
      shell: bash
      # will noop if git tree has not changed (see diff commands below)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Apache Isis Committers (Bot)"
        git add ./docs
        git diff --quiet && git diff --staged --quiet || git commit -m "CI automated site update" -a
        
    - name: Push Site Update
      # uses a predefined action that does exactly this; will noop if git tree has not changed
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUBLISH_TOKEN }}
    
 
# FOR DEBUG USE
#   - name: Dump Env context 
#     env:
#       ENV_CONTEXT: ${{ toJson(env) }}
#     run: echo "$ENV_CONTEXT"
#   - name: Dump GitHub context 
#     env:
#       GITHUB_CONTEXT: ${{ toJson(github) }}
#     run: echo "$GITHUB_CONTEXT"
#   - name: Dump job context
#     env:
#       JOB_CONTEXT: ${{ toJson(job) }}
#     run: echo "$JOB_CONTEXT"
#   - name: Dump steps context
#     env:
#       STEPS_CONTEXT: ${{ toJson(steps) }}
#     run: echo "$STEPS_CONTEXT"
#   - name: Dump runner context
#     env:
#       RUNNER_CONTEXT: ${{ toJson(runner) }}
#     run: echo "$RUNNER_CONTEXT"
#   - name: Dump strategy context
#     env:
#       STRATEGY_CONTEXT: ${{ toJson(strategy) }}
#     run: echo "$STRATEGY_CONTEXT"
#   - name: Dump matrix context
#     env:
#       MATRIX_CONTEXT: ${{ toJson(matrix) }}
#     run: echo "$MATRIX_CONTEXT"
#   - name: Create issue using REST API (example)
#     run: |
#       curl --request POST \
#       --url https://api.github.com/repos/${{ github.repository }}/issues \
#       --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
#       --header 'content-type: application/json' \
#       --data '{
#         "title": "Automated issue for commit: ${{ github.sha }}",
#         "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
#         }'           
           
