name: Demo Wicket (Deploy)

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy demo-wicket to k8s cluster
    runs-on: ubuntu-latest
    env:
      APPNAME: demo-wicket

    strategy:
      matrix:
        branch:
          - jdo
          - jpa

    steps:
    - name: Export APPNAME as output
      id: appname
      shell: bash
      run: |
        echo "##[set-output name=appname;]${APPNAME}"

    - name: Checkout current repo
      uses: actions/checkout@v2.4.0

    - name: Install yq
      shell: bash
      run: |
        sudo snap install yq

    - name: Update scripts
      shell: bash
      run: |
        sh k8s/update.sh $APPNAME ${{ matrix.branch }} VARIANT_IN_IMAGE_NAME

    - name: "kubectl apply -f deployment.yml"
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
      with:
        args: apply -f k8s/${{ steps.appname.outputs.appname }}/deployment.yaml
