name: Demo Wicket (Deploy)

on:
  workflow_dispatch

# https://github.com/marketplace/actions/kubernetes-cli-kubectl
jobs:
  deploy:
    name: Deploy demo-wicket to k8s cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2.3.3
      - name: Deploy to cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
        with:
          args: apply -f k8s/demo-wicket/deployment.yaml
