name: Demo Wicket (Undeploy)

on:
  workflow_dispatch

jobs:
  deploy:
    name: Undeploy demo-wicket from k8s cluster
    runs-on: ubuntu-latest
    env:
      APPNAME: demo-wicket

    strategy:
      matrix:
        branch:
          - jdo
          - jpa

    steps:
      - name: Export APPNAME as output
        id: appname
        shell: bash
        run: |
          echo "##[set-output name=appname;]${APPNAME}"

      - name: Checkout current repo
        uses: actions/checkout@v2.3.5

      - name: Install yq
        shell: bash
        run: |
          sudo snap install yq

      - name: Update scripts
        shell: bash
        run: |
          sh k8s/update.sh $APPNAME ${{ matrix.branch }} VARIANT_IN_IMAGE_NAME

      - name: "kubectl delete -f deployment.yml"
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
        with:
          args: delete -f k8s/${{ steps.appname.outputs.appname }}/deployment.yaml --force --grace-period=0
