name: Hello World (Undeploy)

on:
  workflow_dispatch

jobs:
  deploy:
    name: undeploy simpleapp from k8s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy to cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
        with:
          args: delete -f k8s/helloworld/deployment.yaml
