name: Hello World (Deploy)

on:
  workflow_dispatch

jobs:
  deploy:
    name: deploy simpleapp to k8s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy to cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
        with:
          args: apply -f k8s/simpleapp/deployment.yaml
