name: Hello World (Deploy)

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy helloworld to k8s cluster (helloworld.isis.incode.work)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2.3.3
      - name: Deploy to cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
        with:
          args: apply -f k8s/helloworld/deployment.yaml
