name: Simpleapp (Deploy)

on:
  workflow_dispatch:
  schedule:
    ## daily 04:15 (UTC) in the morning
    - cron: '15 4 * * *'

jobs:
  deploy:
    name: Deploy to k8s cluster
    runs-on: ubuntu-latest
    env:
      APPNAME: simpleapp

    strategy:
      matrix:
        branch:
          - jdo
          - jpa
          - jdo-SNAPSHOT
          - jpa-SNAPSHOT

    steps:
      - name: Export APPNAME as output
        id: appname
        shell: bash
        run: |
          echo "##[set-output name=appname;]${APPNAME}"

      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Install yq
        shell: bash
        run: |
          sudo snap install yq

      - name: Update scripts
        shell: bash
        run: |
          sh k8s/update.sh $APPNAME ${{ matrix.branch }}

      - name: "kubectl apply -f deployment.yml"
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
        with:
          args: apply -f k8s/${{ steps.appname.outputs.appname }}/deployment.yaml
