name: Simpleapp (Deploy)

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy simpleapp to k8s cluster (simpleapp.isis.incode.work)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch:
          - jdo

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2.3.4

      - name: Install yq
        shell: bash
        run: |
          sudo snap install yq

      - name: Update scripts
        shell: bash
        run: |
          APP_NAME="isis-app-simpleapp-${{ matrix.branch }}"
          yq eval ".metadata.name = \"$APP_NAME\"" k8s/simpleapp/010-deployment.yaml -M -i
          yq eval ".spec.selector.matchLabels.app = \"$APP_NAME\"" k8s/simpleapp/010-deployment.yaml -M -i
          yq eval ".spec.template.metadata.labels.app = \"$APP_NAME\"" k8s/simpleapp/010-deployment.yaml -M -i
          yq eval ".spec.template.spec.containers[0].name = \"$APP_NAME\"" k8s/simpleapp/010-deployment.yaml -M -i
          cat k8s/simpleapp/010-deployment.yaml
          yq eval '.metadata.name = "$APP_NAME"' k8s/simpleapp/020-service.yaml -M -i
          cat k8s/simpleapp/020-service.yaml
          yq eval '.metadata.name = "$APP_NAME"' k8s/simpleapp/030-ingress.yaml -M -i
          cat k8s/simpleapp/030-ingress.yaml

#      - name: "kubectl apply -f deployment.yml"
#        uses: actions-hub/kubectl@master
#        env:
#          KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
#        with:
#          args: apply -f k8s/simpleapp/010-deployment.yaml
#
#      - name: "kubectl apply -f service.yml"
#        uses: actions-hub/kubectl@master
#        env:
#          KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
#        with:
#          args: apply -f k8s/simpleapp/020-service.yaml
#
#      - name: "kubectl apply -f ingress.yml"
#        uses: actions-hub/kubectl@master
#        env:
#          KUBE_CONFIG: ${{ secrets.K3D_INCODE_WORK_KUBE_CONFIG }}
#        with:
#          args: apply -f k8s/simpleapp/030-ingress.yaml
